version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: node:12

commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package.jsoon" }}

  save_npm:
    steps:
      - save_cache:
        name: Cache npm dependencies
        key: npm-{{ checksum "package.jsoon" }}
        paths:
          - ~/workspace/node_modules

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm Install
      - save_npm

  lint:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Lint
          command: npm run lint
      - save_npm

  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Build
          command: npm run build
      - save_npm

  test:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Test
          command: npm run test:unit
      - save_npm

workflows:
  pull-request:
    jobs:
      - setup
      - lint:
          requitres:
            - setup
      - build:
          requitres:
            - lint
      - test:
          requitres:
            - build








